// Navigation and local learning history. No analytics leave this browser.
const HISTORY_KEY = 'english-learning-history-v1';
let historyData = {days:{}, answers:{}, reviews:{}, lastLesson:0};
let storageAvailable = true;
try { const saved=JSON.parse(localStorage.getItem(HISTORY_KEY)); if(saved && saved.days && saved.answers && saved.reviews) historyData=saved; } catch { storageAvailable=false; }
function persistHistory(){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(historyData));}catch{storageAvailable=false;} renderStats();}
function activity(kind){const d=localDay(); if(!historyData.days[d])historyData.days[d]={};historyData.days[d][kind]=true;persistHistory();}
function recordAnswer(key,correct){if(!historyData.answers[key])historyData.answers[key]={first:correct,latest:correct};else historyData.answers[key].latest=correct;activity('练习');}
const sections=[...document.querySelectorAll('.wrap > section')];
sections[0].id='home';sections[sections.length-1].id='planSection';
const routes={home:['home'],beginner:['beginner'],workplace:['workplace'],vocab:['vocab'],practice:['map','scenes','cards','mail','speak','quiz','planSection'],stats:['stats']};
const nav=document.querySelector('.nav');
nav.innerHTML='<a class="brand" href="#home">英语学习台<small>从校园到职场 · 中文带学</small></a><nav aria-label="主导航">'+[['home','学习首页'],['beginner','新人课程'],['workplace','外企词典'],['vocab','单词表'],['practice','练习工具'],['stats','学习统计']].map(([id,label])=>`<a href="#${id}" data-route="${id}">${label}</a>`).join('')+'</nav>';
const statsSection=document.createElement('section');statsSection.id='stats';statsSection.innerHTML='<span class="pill">MY LEARNING</span><h2>看见自己的进步</h2><p class="muted">统计只保存在当前浏览器。学习天数按实际练习计入；浏览页面不会增加记录。历史课程完成度会保留，学习日期与答题数据从此版本开始记录。</p><div id="statsContent"></div>';document.querySelector('.wrap').insertBefore(statsSection,document.querySelector('footer'));
const practiceNav=document.createElement('nav');practiceNav.id='practiceNav';practiceNav.setAttribute('aria-label','练习工具导航');practiceNav.className='toolbar';practiceNav.innerHTML=[['map','表达骨架'],['scenes','场景'],['cards','句卡'],['mail','邮件'],['speak','口语'],['quiz','测验']].map(([id,label])=>`<a class="btn ghost" href="#${id}">${label}</a>`).join('');document.getElementById('map').prepend(practiceNav);
const dashboard=document.createElement('div');dashboard.className='card';dashboard.id='homeDashboard';sections[0].append(dashboard);
function route(){const target=location.hash.slice(1)||'home';const page=Object.keys(routes).find(key=>key===target||routes[key].includes(target))||'home';document.querySelectorAll('.wrap > section').forEach(s=>s.hidden=!routes[page].includes(s.id));document.querySelectorAll('[data-route]').forEach(a=>{if(a.dataset.route===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(page==='stats')renderStats();if(target!==page&&document.getElementById(target))document.getElementById(target).scrollIntoView();else window.scrollTo(0,0);}
window.addEventListener('hashchange',route);
function dateKey(offset){const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
function renderStats(){
 const answers=Object.values(historyData.answers);const right=answers.filter(a=>a.first).length;const active=Object.keys(historyData.days).length;let streak=0;let offset=historyData.days[dateKey(0)]?0:-1;while(historyData.days[dateKey(offset)]){streak++;offset--;}
 const completed=new Set(completedLessons).size;
 const metrics=[['完成课程',`${completed} / 7`],['累计学习',`${active} 天`],['连续学习',`${streak} 天`],['首次答对',answers.length?`${Math.round(right/answers.length*100)}%`:'暂无']];
 const wrong=Object.entries(historyData.answers).filter(([,a])=>!a.latest);
 document.getElementById('statsContent').innerHTML=`<div class="grid g4">${metrics.map(([label,value])=>`<article class="card"><span class="muted">${label}</span><p class="metric">${value}</p></article>`).join('')}</div><p class="muted">首次答对率：${right} / ${answers.length} 道不同题目的首次作答；重试不会提高首次答对率。连续学习允许今天尚未练习，从昨天向前计算。</p><h3>最近 7 天</h3><div class="week-grid">${Array.from({length:7},(_,i)=>{const key=dateKey(i-6);const kinds=Object.keys(historyData.days[key]||{});return `<div class="day-cell ${kinds.length?'active':''}"><strong>${i===6?'今天':key.split('-').slice(1).join('/')}</strong><p>${kinds.length?'已练习':'未练习'}</p><small>${kinds.join(' · ')}</small></div>`;}).join('')}</div><h3>需要再练一遍 · ${wrong.length} 题</h3>${wrong.length?wrong.map(([key])=>{const [type,id]=key.split(':');return `<button class="opt" onclick="reviewQuestion('${type}',${Number(id)})">${type==='lesson'?LESSONS[Number(id)].title:QUIZ[Number(id)].q} → 再练习</button>`;}).join(''):'<p class="feedback">目前没有待复习错题。完成情景题后，这里会显示需要再练的内容。</p>'}<h3>句卡掌握情况</h3><p>自评已掌握 ${Object.values(historyData.reviews).filter(v=>v==='known').length} 张 · 待复习 ${Object.values(historyData.reviews).filter(v=>v==='again').length} 张</p><a href="#cards">去练句卡 →</a><p class="muted">${storageAvailable?'记录已保存在本机，不跨设备同步。':'浏览器无法保存记录，本次数据可能在关闭后丢失。'}</p>`;
 document.getElementById('homeDashboard').innerHTML=`<h3>你的学习旅程</h3><p>已完成 ${completed} / 7 课 · 累计学习 ${active} 天</p><progress max="7" value="${completed}" aria-label="课程完成进度"></progress><div class="toolbar"><button class="btn olive" onclick="continueLearning()">继续学习 →</button><a class="btn ghost" href="#vocab">去背单词表</a><a class="btn ghost" href="#stats">查看学习统计</a></div><p class="muted">今天的小目标：完成一课，再背 8 个单词。</p>`;
}
function continueLearning(){const i=Number.isInteger(historyData.lastLesson)?historyData.lastLesson:0;showLesson(Math.min(6,Math.max(0,i)));location.hash='beginner';}
function reviewQuestion(type,id){if(type==='lesson'){showLesson(id);location.hash='beginner';}else{location.hash='quiz';route();document.querySelector(`.opt[data-q="${id}"]`).closest('.q').scrollIntoView({block:'center'});}}
const originalShowLesson=showLesson;
showLesson=function(i){originalShowLesson(i);historyData.lastLesson=i;persistHistory();const controls=document.createElement('div');controls.className='toolbar';controls.innerHTML=`<button class="btn ghost" onclick="showLesson(${i-1});document.getElementById('beginner').scrollIntoView()" ${i===0?'disabled':''}>← 上一课</button><span class="muted">${i+1} / 7 · ${LESSONS[i].title}</span><button class="btn ghost" onclick="showLesson(${i+1});document.getElementById('beginner').scrollIntoView()" ${i===6?'disabled':''}>下一课 →</button>`;document.getElementById('lessonPanel').prepend(controls);};
const originalAnswer=answerLesson;answerLesson=function(answer){originalAnswer(answer);recordAnswer(`lesson:${lessonIndex}`,lessonPassed);};
const originalFinish=finishLesson;finishLesson=function(){originalFinish();if(lessonPassed){activity('课程');const b=document.getElementById('finishLesson');b.disabled=true;b.textContent='✓ 本课已完成';}};
const originalSpeak=speakEnglish;speakEnglish=function(text){originalSpeak(text);if(text&&window.speechSynthesis)activity('听读');};
const originalGrade=gradeQuiz;gradeQuiz=function(){const selected=document.querySelectorAll('#quizBox .picked');if(selected.length!==QUIZ.length){document.getElementById('quizResult').textContent=`还有 ${QUIZ.length-selected.length} 题未作答，请完成后交卷。`;return;}originalGrade();selected.forEach(b=>recordAnswer(`quiz:${b.dataset.q}`,Number(b.dataset.i)===QUIZ[Number(b.dataset.q)].a));};
const originalMark=mark;mark=function(key){originalMark(key);if(key==='speak')activity('口语');if(key==='mail')activity('邮件');};
const reviewControls=document.createElement('div');reviewControls.className='toolbar';reviewControls.innerHTML='<button class="btn ghost" onclick="rateCard(\'again\')">还不熟 · 加入复习</button><button class="btn olive" onclick="rateCard(\'known\')">我会说了</button><span id="cardFeedback" role="status"></span>';document.getElementById('cards').append(reviewControls);
function rateCard(value){const c=currentCards()[cardIndex];historyData.reviews[c.en]=value;activity('句卡');document.getElementById('cardFeedback').textContent=value==='known'?'已记为掌握，继续下一张。':'已加入待复习，再读一次试试。';if(value==='known')nextCard();}
const reviewButton=document.createElement('button');reviewButton.className='btn ghost';reviewButton.textContent='只练待复习句卡';let reviewOnly=false;const originalCurrentCards=currentCards;currentCards=function(){const list=originalCurrentCards();if(!reviewOnly)return list;const filtered=list.filter(c=>historyData.reviews[c.en]==='again');return filtered.length?filtered:list;};reviewButton.onclick=()=>{reviewOnly=!reviewOnly;reviewButton.textContent=reviewOnly?'退出复习模式':'只练待复习句卡';cardIndex=0;showCard();document.getElementById('cardFeedback').textContent=reviewOnly&&!originalCurrentCards().some(c=>historyData.reviews[c.en]==='again')?'当前场景没有待复习句卡，先展示全部句卡。':'';};reviewControls.prepend(reviewButton);
showLesson(Math.min(6,Math.max(0,Number(historyData.lastLesson)||0)));renderStats();route();
